### ISSUE TITLE
latest (4.3) rapiddisk module does not build on Linux 4.8.x

### ISSUE THREAD

**Issue by marcelhuberfoo** [pkoutoupis/rapiddisk#2]
When dkms compiling the module, I get the following errors:

```
DKMS make.log for rapiddisk-4.3 for kernel 4.8.2-1-ARCH (x86_64)
Wed Oct 19 22:24:11 CEST 2016
make: Entering directory '/usr/lib/modules/4.8.2-1-ARCH/build'
  LD      /var/lib/dkms/rapiddisk/4.3/build/built-in.o
  CC [M]  /var/lib/dkms/rapiddisk/4.3/build/rapiddisk.o
In file included from ./include/linux/init.h:4:0,
                 from /var/lib/dkms/rapiddisk/4.3/build/rapiddisk.c:14:
/var/lib/dkms/rapiddisk/4.3/build/rapiddisk.c: In function ‘rdsk_make_request’:
/var/lib/dkms/rapiddisk/4.3/build/rapiddisk.c:494:18: error: ‘struct bio’ has no member named ‘bi_rw’; did you mean ‘bi_opf’?
  if (unlikely(bio->bi_rw & REQ_DISCARD)) {
                  ^
./include/linux/compiler.h:168:42: note: in definition of macro ‘unlikely’
 # define unlikely(x) __builtin_expect(!!(x), 0)
                                          ^
/var/lib/dkms/rapiddisk/4.3/build/rapiddisk.c:494:28: error: ‘REQ_DISCARD’ undeclared (first use in this function)
  if (unlikely(bio->bi_rw & REQ_DISCARD)) {
                            ^
./include/linux/compiler.h:168:42: note: in definition of macro ‘unlikely’
 # define unlikely(x) __builtin_expect(!!(x), 0)
                                          ^
/var/lib/dkms/rapiddisk/4.3/build/rapiddisk.c:494:28: note: each undeclared identifier is reported only once for each function it appears in
  if (unlikely(bio->bi_rw & REQ_DISCARD)) {
                            ^
./include/linux/compiler.h:168:42: note: in definition of macro ‘unlikely’
 # define unlikely(x) __builtin_expect(!!(x), 0)
                                          ^
/var/lib/dkms/rapiddisk/4.3/build/rapiddisk.c:514:7: error: implicit declaration of function ‘bio_rw’ [-Werror=implicit-function-declaration]
  rw = bio_rw(bio);
       ^~~~~~
/var/lib/dkms/rapiddisk/4.3/build/rapiddisk.c:515:12: error: ‘READA’ undeclared (first use in this function)
  if (rw == READA)
            ^~~~~
cc1: some warnings being treated as errors
make[1]: *** [scripts/Makefile.build:296: /var/lib/dkms/rapiddisk/4.3/build/rapiddisk.o] Error 1
make: *** [Makefile:1471: _module_/var/lib/dkms/rapiddisk/4.3/build] Error 2
make: Leaving directory '/usr/lib/modules/4.8.2-1-ARCH/build'

```
As I currently do not have much time to investigate or correct, I leave it to you.

Thank you in advance for looking at it.

**Comment by pkoutoupis** [comment]
I will be adding support for the 4.8 (and 4.9) kernels shortly. Thank you.

**Comment by pkoutoupis** [comment]
commit da6633129150a89ddb4f0fc147f4f91b31593c14
Author: Petros Koutoupis <petros@petroskoutoupis.com>
Date:   Fri Oct 28 14:23:34 2016 -0500

    Adding 4.8 & 4.9 kernel support and releasing 4.4
