### ISSUE TITLE
Unable to build on RHEL8.4 - backports!

### ISSUE THREAD

**Issue by dannygoulder** [pkoutoupis/rapiddisk#63]
Hi,

Just tried to build rapiddisk on RHEL8.4 (4.18 kernel with lots of backports).

```
rapiddisk/module/rapiddisk.c:643:4: error: implicit declaration of function ‘kill_bdev’; did you mean ‘thaw_bdev’? [-Werror=implicit-function-declaration]
    kill_bdev(bdev);
    ^~~~~~~~~
    thaw_bdev
```

Seems as though they must have backported https://github.com/torvalds/linux/commit/3373a3461aa15b7f9a871fa4cb2c9ef21ac20b47 to their 8.4 release, which has tricked the compiler into using the static'd function.  Joy!

Removing the kernel version check and forcing invalidate_bdev allows it to build cleanly on my system, but obviously won't do for a PR.

I can't see any conditional code elsewhere in the module that refers to anything other than pure kernel versions so I'm unsure the best way to try to address the condition where RHEL8.4+ is being used.

Happy to take guidance and submit a PR though :)

**Comment by pkoutoupis** [comment]
@dannygoulder: Thank you for submitting this. I am just trying to confirm: is this only present in 8.4 or does it also exist in 8.3 (and earlier 8.x version of RHEL/CentOS)?

**Comment by pkoutoupis** [comment]
@dannygoulder : does this work for you?
```
diff --git a/module/rapiddisk.c b/module/rapiddisk.c
index 8773cbe..18320de 100644
--- a/module/rapiddisk.c
+++ b/module/rapiddisk.c
@@ -637,7 +637,7 @@ static int rdsk_ioctl(struct block_device *bdev, fmode_t mode,
                error = -EBUSY;
                if (bdev->bd_openers <= 1) {
 #if LINUX_VERSION_CODE >= KERNEL_VERSION(3,3,0)
-#if LINUX_VERSION_CODE >= KERNEL_VERSION(5,8,0)
+#if LINUX_VERSION_CODE >= KERNEL_VERSION(5,8,0) || (defined(RHEL_MAJOR) && RHEL_MAJOR == 8 && RHEL_MINOR >= 4)
                        invalidate_bdev(bdev);
 #else
                        kill_bdev(bdev);
```
I just need to make sure that it was introduced in 8.4 and not earlier.

**Comment by dannygoulder** [comment]
You beat me to it:

```
[dgoulder@DESKTOP-IK2DVS7 kernels]$ diff -u 4.18.0-*/include/linux/fs.h | egrep "^[-+][-+]|kill_bdev"
--- 4.18.0-240.22.1.el8_3.x86_64/include/linux/fs.h	2021-03-25 22:45:50.000000000 +0400
+++ 4.18.0-305.3.1.el8_4.x86_64/include/linux/fs.h	2021-05-17 18:20:03.000000000 +0400
-extern void kill_bdev(struct block_device *);
-static inline void kill_bdev(struct block_device *bdev) {}
```

Last 8.3 kernel still had the function

**Comment by dannygoulder** [comment]
Meant to add: thanks so much for such a rapid response.  I'll test the patch now and confirm (but you've probably already done it by now lol).

**Comment by dannygoulder** [comment]
All looks good and build goes through fine now.  Thanks for the awesomely fast response time.

**Comment by pkoutoupis** [comment]
Nice! And you did all the leg work. It just made it easier to figure out how to resolve it. Anyway, I will push it to master within the next few days. Thank you again!

**Comment by pkoutoupis** [comment]
@dannygoulder: It is now merged into master and cut as release 7.2.1: https://github.com/pkoutoupis/rapiddisk/releases/tag/7.2.1

Thanks for your help!
