### ISSUE TITLE
CentOS Stream 9 install problem

### ISSUE THREAD

**Issue by imbmf** [pkoutoupis/rapiddisk#169]
Greetings,
i am trying to install rapiddisk with dkms support on CentOS Stream 9 but I am getting this error:
[root@test-centos rapiddisk-master]# make dkms-install
make -C module dkms-install
make[1]: Entering directory '/root/rapiddisk-master/module'
rm -rf *.o *.ko *.symvers *.mod.c .*.cmd Module.markers modules.order *.o.* built-in*
rm -rf .tmp_versions .rapiddisk.o.d .rapiddisk-cache.o.d *.unsigned *.sdtinfo.c .ctf/ .cache.mk *.mod
rm -f /lib/modules/5.14.0-316.el9.x86_64/kernel/drivers/block/rapiddisk.ko
rm -f /lib/modules/5.14.0-316.el9.x86_64/kernel/drivers/block/rapiddisk-cache.ko
depmod -a
dkms add . || true
Error! DKMS tree already contains: rapiddisk-9.1.0
You cannot add the same module/version combo more than once.
dkms install rapiddisk/9.1.0 -k 5.14.0-316.el9.x86_64
Sign command: /lib/modules/5.14.0-316.el9.x86_64/build/scripts/sign-file
Signing key: /var/lib/dkms/mok.key
Public certificate (MOK): /var/lib/dkms/mok.pub

Building module:
Cleaning build area...
make -j2 KERNELRELEASE=5.14.0-316.el9.x86_64 -C /lib/modules/5.14.0-316.el9.x86_64/build M=/var/lib/dkms/rapiddisk/9.1.0/build....(bad exit status: 2)
Error! Bad return status for module build on kernel: 5.14.0-316.el9.x86_64 (x86_64)
Consult /var/lib/dkms/rapiddisk/9.1.0/build/make.log for more information.
make[1]: *** [Makefile:61: dkms-install] Error 10
make[1]: Leaving directory '/root/rapiddisk-master/module'
make: *** [Makefile:29: module] Error 2

This is the make.log file
[root@test-centos rapiddisk-master]# cat /var/lib/dkms/rapiddisk/9.1.0/build/make.log
DKMS make.log for rapiddisk-9.1.0 for kernel 5.14.0-316.el9.x86_64 (x86_64)
Fri May 26 01:46:51 PM EDT 2023
make[2]: Entering directory '/usr/src/kernels/5.14.0-316.el9.x86_64'
  CC [M]  /var/lib/dkms/rapiddisk/9.1.0/build/rapiddisk.o
  CC [M]  /var/lib/dkms/rapiddisk/9.1.0/build/rapiddisk-cache.o
/var/lib/dkms/rapiddisk/9.1.0/build/rapiddisk-cache.c: In function ‘dm_io_async_bvec’:
/var/lib/dkms/rapiddisk/9.1.0/build/rapiddisk-cache.c:181:14: error: ‘struct dm_io_request’ has no member named ‘bi_op’; did you mean ‘bi_opf’?
  181 |         iorq.bi_op = rw;
      |              ^~~~~
      |              bi_opf
/var/lib/dkms/rapiddisk/9.1.0/build/rapiddisk-cache.c:182:13: error: ‘struct dm_io_request’ has no member named ‘bi_op_flags’
  182 |         iorq.bi_op_flags = 0;
      |             ^
make[3]: *** [scripts/Makefile.build:297: /var/lib/dkms/rapiddisk/9.1.0/build/rapiddisk-cache.o] Error 1
make[3]: *** Waiting for unfinished jobs....
/var/lib/dkms/rapiddisk/9.1.0/build/rapiddisk.c: In function ‘detach_device’:
/var/lib/dkms/rapiddisk/9.1.0/build/rapiddisk.c:932:9: error: implicit declaration of function ‘blk_cleanup_queue’; did you mean ‘blk_put_queue’? [-Werror=implicit-function-declaration]
  932 |         blk_cleanup_queue(rdsk->rdsk_queue);
      |         ^~~~~~~~~~~~~~~~~
      |         blk_put_queue
cc1: all warnings being treated as errors
make[3]: *** [scripts/Makefile.build:297: /var/lib/dkms/rapiddisk/9.1.0/build/rapiddisk.o] Error 1
make[2]: *** [Makefile:1924: /var/lib/dkms/rapiddisk/9.1.0/build] Error 2
make[2]: Leaving directory '/usr/src/kernels/5.14.0-316.el9.x86_64'

**Comment by pkoutoupis** [comment]
@imbmf Thank you for sharing this. I will look into the 5.14.0-316.el9 kernel and find a resolution soon.

**Comment by imbmf** [comment]
hi for sure, but i need more instructions how to do it. :)

**Comment by pkoutoupis** [comment]
Oh, sorry. I should have provided something in the way of instructions. The above code can be copied into a file anywhere on your system containing the source code. Note that this patch is based from the HEAD of the master branch of this repository.

Once you save it to the file (for instance, named rapiddisk.patch), change into the rapiddisk source directory and run:
```
# patch -p1<../rapiddisk.patch 
```
If successful, you should see something like this:
```
patching file module/rapiddisk-cache.c
patching file module/rapiddisk.c
```
If you instead see something like this, something went wrong:
```
can't find file to patch at input line 5
Perhaps you used the wrong -p or --strip option?
The text leading up to this was:
--------------------------
|diff --git a/module/rapiddisk-cache.c b/module/rapiddisk-cache.c
|index 9f6a234..ae77d73 100644
|--- a/module/rapiddisk-cache.c
|+++ b/module/rapiddisk-cache.c
--------------------------
File to patch:
```
There could be a number of reasons for it. The first of which could be the fact that the tabs were not preserved in the copying of the patch code and you may need to sed replace the spaces into tabs.

Anyway, in the next day or so, I will push a development branch. I got this to work on CentOS Stream 9 and Rocky Linux 9.2.

**Comment by imbmf** [comment]
this is the output from command:
[root@test-centos rapiddisk-master]# patch -p1<../rapiddisk.patch
patching file module/rapiddisk-cache.c
Hunk #1 FAILED at 177.
1 out of 1 hunk FAILED -- saving rejects to file module/rapiddisk-cache.c.rej
patching file module/rapiddisk.c
Hunk #1 FAILED at 75.
Hunk #2 FAILED at 928.
2 out of 2 hunks FAILED -- saving rejects to file module/rapiddisk.c.rej

**Comment by pkoutoupis** [comment]
OK. No worries. I will try to get a development branch up today.

**Comment by pkoutoupis** [comment]
Ok. I pushed [https://github.com/pkoutoupis/rapiddisk/tree/feature/add_new_rhel9_kernel_support](https://github.com/pkoutoupis/rapiddisk/tree/feature/add_new_rhel9_kernel_support). To check out the branch and build, either `git clone` the repo or if you already have a local copy, then `git pull`. Then do a `git checkout feature/add_new_rhel9_kernel_support`. Verify that you are in that feature/add_new_rhel9_kernel_support branch by typing `git branch`. Run a `make` and hopefully, you should get a successful module build.

**Comment by matteotenca** [comment]
Hi @pkoutoupis and @imbmf !

It seems to be ok now:

```bash
shub@localhost:~/rapiddisk$ cat /etc/redhat-release
CentOS Stream release 9
shub@localhost:~/rapiddisk$ uname -a
Linux localhost.localdomain 5.14.0-319.el9.x86_64 #1 SMP PREEMPT_DYNAMIC Thu May 25 19:53:58 UTC 2023 x86_64 x86_64 x86_64 GNU/Linux
shub@localhost:~$ git clone https://github.com/pkoutoupis/rapiddisk.git
Cloning into 'rapiddisk'...
remote: Enumerating objects: 2783, done.
remote: Counting objects: 100% (318/318), done.
remote: Compressing objects: 100% (210/210), done.
remote: Total 2783 (delta 137), reused 146 (delta 107), pack-reused 2465
Receiving objects: 100% (2783/2783), 1.11 MiB | 10.19 MiB/s, done.
Resolving deltas: 100% (1814/1814), done.
shub@localhost:~$ cd rapiddisk
shub@localhost:~/rapiddisk$ git checkout feature/add_new_rhel9_kernel_support
branch 'feature/add_new_rhel9_kernel_support' set up to track 'origin/feature/add_new_rhel9_kernel_support'.
Switched to a new branch 'feature/add_new_rhel9_kernel_support'
shub@localhost:~/rapiddisk$ sudo make dkms-install
make -C module dkms-install
make[1]: Entering directory '/home/shub/rapiddisk/module'
rm -rf *.o *.ko *.symvers *.mod.c .*.cmd Module.markers modules.order *.o.* built-in*
rm -rf .tmp_versions .rapiddisk.o.d .rapiddisk-cache.o.d *.unsigned *.sdtinfo.c .ctf/ .cache.mk *.mod
rm -f /lib/modules/5.14.0-319.el9.x86_64/kernel/drivers/block/rapiddisk.ko
rm -f /lib/modules/5.14.0-319.el9.x86_64/kernel/drivers/block/rapiddisk-cache.ko
depmod -a
dkms add . || true
Creating symlink /var/lib/dkms/rapiddisk/9.1.0/source -> /usr/src/rapiddisk-9.1.0
dkms install rapiddisk/9.1.0 -k 5.14.0-319.el9.x86_64
Sign command: /lib/modules/5.14.0-319.el9.x86_64/build/scripts/sign-file
Signing key: /var/lib/dkms/mok.key
Public certificate (MOK): /var/lib/dkms/mok.pub

Building module:
Cleaning build area...
make -j3 KERNELRELEASE=5.14.0-319.el9.x86_64 -C /lib/modules/5.14.0-319.el9.x86_64/build M=/var/lib/dkms/rapiddisk/9.1.0/build...
Signing module /var/lib/dkms/rapiddisk/9.1.0/build/rapiddisk.ko
Signing module /var/lib/dkms/rapiddisk/9.1.0/build/rapiddisk-cache.ko
Cleaning build area...

rapiddisk.ko.xz:
Running module version sanity check.
 - Original module
   - No original module exists within this kernel
 - Installation
   - Installing to /lib/modules/5.14.0-319.el9.x86_64/extra/

rapiddisk-cache.ko.xz:
Running module version sanity check.
 - Original module
   - No original module exists within this kernel
 - Installation
   - Installing to /lib/modules/5.14.0-319.el9.x86_64/extra/
Adding any weak-modules
depmod....
make[1]: Leaving directory '/home/shub/rapiddisk/module'
shub@localhost:~/rapiddisk$ 
```

**Comment by imbmf** [comment]
Hi,
I can confirm that compilation and instalation works now.
[root@test-centos rapiddisk]# make dkms-install
make -C module dkms-install
make[1]: Entering directory '/root/rapiddisk/module'
rm -rf *.o *.ko *.symvers *.mod.c .*.cmd Module.markers modules.order *.o.* built-in*
rm -rf .tmp_versions .rapiddisk.o.d .rapiddisk-cache.o.d *.unsigned *.sdtinfo.c .ctf/ .cache.mk *.mod
rm -f /lib/modules/5.14.0-316.el9.x86_64/kernel/drivers/block/rapiddisk.ko
rm -f /lib/modules/5.14.0-316.el9.x86_64/kernel/drivers/block/rapiddisk-cache.ko
depmod -a
dkms add . || true
Error! DKMS tree already contains: rapiddisk-9.1.0
You cannot add the same module/version combo more than once.
dkms install rapiddisk/9.1.0 -k 5.14.0-316.el9.x86_64
Sign command: /lib/modules/5.14.0-316.el9.x86_64/build/scripts/sign-file
Signing key: /var/lib/dkms/mok.key
Public certificate (MOK): /var/lib/dkms/mok.pub

Building module:
Cleaning build area...
make -j2 KERNELRELEASE=5.14.0-316.el9.x86_64 -C /lib/modules/5.14.0-316.el9.x86_64/build M=/var/lib/dkms/rapiddisk/9.1.0/build....
Signing module /var/lib/dkms/rapiddisk/9.1.0/build/rapiddisk.ko
Signing module /var/lib/dkms/rapiddisk/9.1.0/build/rapiddisk-cache.ko
Cleaning build area...

rapiddisk.ko.xz:
Running module version sanity check.
 - Original module
   - No original module exists within this kernel
 - Installation
   - Installing to /lib/modules/5.14.0-316.el9.x86_64/extra/

rapiddisk-cache.ko.xz:
Running module version sanity check.
 - Original module
   - No original module exists within this kernel
 - Installation
   - Installing to /lib/modules/5.14.0-316.el9.x86_64/extra/
Adding any weak-modules
depmod......
make[1]: Leaving directory '/root/rapiddisk/module'

**Comment by pkoutoupis** [comment]
OK. Thank you. I will clean up the patch and push to master hopefully this week.

What is interesting is that this kernel change appears in RHEL 9.2 kernel and later (which affects the current CentOS Stream 9). I need to find a clever way to address both the changes of RHEL 9.1/9.2 and the current CentOS. I have an idea which I will be testing out this week.

**Comment by matteotenca** [comment]
@pkoutoupis 

But what changed in the 5.14.xx versions? I tried using kernel 6.xx under Centos 9 and no problems arised. I am asking just because I am curious. :-)

**Comment by pkoutoupis** [comment]
@matteotenca In this particular case, I do not believe it is specific the 5.14.xx kernel source. RHEL kernels are what I have historically called _Franken-kernels_. Backported patches (usually security related) of later kernel are adopted to ensure stability. In many cases, this will break compatibility to external drivers when underlying subsystems are modified in that particular release. In our case, this occurred somewhere between the kernels of RHEL 9.1 and 9.2.

Note that the way Red Hat maintains their kernel just means that it is not consistent with what is upstream.

As to why 6.x doesn't experience issues....that is because the right "define" checks are in place to ensure that the compiler is picking up the right pieces of code.

**Comment by pkoutoupis** [comment]
Merged in master.
